FROM bellsoft/liberica-openjdk-alpine:17
ARG JAR_PATH=/build/libs/*.jar
COPY ${JAR_PATH} /home/server.jar
ARG ACTIVE_PROFILE
ENV ACTIVE_PROFILE=${ACTIVE_PROFILE}
ARG DATASOURCE_URL_LOCAL
ENV DATASOURCE_URL_LOCAL=${DATASOURCE_URL_LOCAL}
ARG DATASOURCE_USERNAME
ENV DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
ARG DATASOURCE_PASSWORD
ENV DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
ARG DATASOURCE_URL_DEV
ENV DATASOURCE_URL_DEV=${DATASOURCE_URL_DEV}
ARG DATASOURCE_URL_PROD
ENV DATASOURCE_URL_PROD=${DATASOURCE_URL_PROD}
ENTRYPOINT ["java","-jar","/home/server.jar"]
