spring:
  profiles:
    group:
      "local": "localDB, devPort, secret, web-mvc"
      "dev": "devDB, devPort, secret, web-mvc"
      "prod": "prodDB, prodPort, secret, web-mvc"
    active: ${ACTIVE_PROFILE}

---

spring:
  config:
    activate:
      on-profile: "localDB" # MySQL ver 8


  datasource:
    url: ${DATASOURCE_URL_LOCAL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1
  sql:
    init:
      platform: mysql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  KAKAO_API_KEY: ${KAKAO_API_KEY}
  KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  mail:
    request_Uri: ${MAIL_REQUEST_URI}

  cloud:
    aws:
      s3:
        bucket: ${BUCKET_NAME}
      stack.auto: false
      region.static: ap-northeast-2
      credentials:
        accessKey: ${ACCESS_KEY}
        secretKey: ${SECRET_KEY}

---

spring:
  config:
    activate:
      on-profile: "devDB"

  datasource:
    url: ${DATASOURCE_URL_DEV}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1
  sql:
    init:
      platform: mysql
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  KAKAO_API_KEY: ${KAKAO_API_KEY}
  KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  mail:
    request_Uri: ${MAIL_REQUEST_URI}

  cloud:
    aws:
      s3:
        bucket: ${BUCKET_NAME}
      stack.auto: false
      region.static: ap-northeast-2
      credentials:
        accessKey: ${ACCESS_KEY}
        secretKey: ${SECRET_KEY}
---

spring:
  config:
    activate:
      on-profile: "prodDB"

  datasource:
    url: ${DATASOURCE_URL_PROD}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1
  sql:
    init:
      platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  KAKAO_API_KEY: ${KAKAO_API_KEY}
  KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  mail:
    request_Uri: ${MAIL_REQUEST_URI}

  cloud:
    aws:
      s3:
        bucket: ${BUCKET_NAME}
      stack.auto: false
      region.static: ap-northeast-2
      credentials:
        accessKey: ${ACCESS_KEY}
        secretKey: ${SECRET_KEY}

---

spring:
  config:
    activate:
      on-profile: "devPort"

server:
  port: 9000

---

spring:
  config:
    activate:
      on-profile: "prodPort"

server:
  port: 9001

---

spring:
  config:
    activate:
      on-profile: "secret"

jwt:
  secret: ${JWT_SECRET_KEY}

mail:
  username: ${GOOGLE_EMAIL}
  password: ${GOOGLE_APP_PASSWORD}

---
